### ISSUE TITLE
Build instruction clarification

### ISSUE THREAD

**Issue by stefan-ernst** [regolith-linux/i3-snapshot#1]
Hi @kgilmer 

I just tried to build the snapshot tool locally using the instructions and I have a few observations: 

In order to get the complete directory, the git clone needs to be recursive.

Otherwise:

-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:5 (add_subdirectory):
  The source directory

    /home/stefan/Projects/i3-snapshot/lib/i3ipc++

  does not contain a CMakeLists.txt file.

So git clone --recursive https://github.com/regolith-linux/i3-snapshot.git it is :-)

The following two are required on Eoan for CMAKE:

sudo apt install libsigc++-2.0-dev
sudo apt install libjsoncpp-dev

After that, i3-snapshots builds fine.

Hope this helps!

**Comment by kgilmer** [comment]
Somehow I didn't get the notification when you created this issue @realignedTech .  Thanks for your tips,  I will add them to the readme!
